export const TOGGLE_LOGIN_SIGNUP_MODAL = 'TOGGLE_LOGIN_SIGNUP_MODAL';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const RESET_TOKEN = 'RESET_TOKEN';

export const RESET_LISTING = 'RESET_LISTING';
export const RECEIVE_LISTING = 'RECEIVE_LISTING';
export const RECEIVE_LISTING_SLEEP_ARGMS = 'RECEIVE_LISTING_SLEEP_ARGMS';
export const RECEIVE_CALENDAR = 'RECEIVE_CALENDAR';
export const RECEIVE_LISTINGS = 'RECEIVE_LISTINGS';
export const CHANGE_PUBLISH_LISTING = 'CHANGE_PUBLISH_LISTING';
export const RECEIVE_LISTING_PHOTOS = 'RECEIVE_LISTING_PHOTOS';
export const START_LISTING_LOADING = 'START_LISTING_LOADING';
export const CLEAR_LISTING_LOADING = 'CLEAR_LISTING_LOADING';
export const RECEIVE_LISTING_ERRORS = 'RECEIVE_LISTING_ERRORS';
export const CLEAR_LISTING = 'CLEAR_LISTING';

export const START_REVIEW_LOADING = 'START_REVIEW_LOADING';
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';
export const RECEIVE_REVIEWS_ERRORS = 'RECEIVE_REVIEWS_ERRORS';
export const RECEIVE_REVIEW = 'RECEIVE_REVIEW';
export const REMOVE_REVIEW = 'REMOVE_REVIEW';

export const UPDATE_BOOKING_DATES = 'UPDATE_BOOKING_DATES';
export const UPDATE_BOOKING_GUESTS = 'UPDATE_BOOKING_GUESTS';
export const UPDATE_BOOKING_TOTAL_COST = 'UPDATE_BOOKING_TOTAL_COST';

export const RESET_BOOKING = 'RESET_BOOKING';
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS';
export const RECEIVE_BOOKING = 'RECEIVE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const RECEIVE_BOOKING_ERRORS = 'RECEIVE_BOOKING_ERRORS';
export const CLEAR_BOOKING_ERRORS = 'CLEAR_BOOKING_ERRORS';
export const START_BOOKING_LOADING = 'START_BOOKING_LOADING';

export const FILTERS_REQUEST = 'FILTERS_REQUEST';
export const FILTERS_SUCCESS = 'FILTERS_SUCCESS';
export const FILTERS_FAIL = 'FILTERS_FAIL';
export const UPDATE_DATE_FILTER = 'UPDATE_DATE_FILTER';
export const UPDATE_GUEST_FILTER = 'UPDATE_GUEST_FILTER';
export const UPDATE_HOME_TYPE_FILTER = 'UPDATE_HOME_TYPE_FILTER';
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
